// <auto-generated />
using System;
using HiLoGuessing.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HiLoGuessing.Infrastructure.Migrations
{
    [DbContext(typeof(MysteryNumberDbContext))]
    [Migration("20231111141945_RemoveConstraints")]
    partial class RemoveConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("HiLoGuessing.Infrastructure.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HiLoGuessId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MysteryNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAttempts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HiLoGuessId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("HiLoGuessing.Infrastructure.HiLoGuess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneratedMysteryNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HiLoGuess");
                });

            modelBuilder.Entity("HiLoGuessing.Infrastructure.Attempt", b =>
                {
                    b.HasOne("HiLoGuessing.Infrastructure.HiLoGuess", null)
                        .WithMany("Attempts")
                        .HasForeignKey("HiLoGuessId");
                });

            modelBuilder.Entity("HiLoGuessing.Infrastructure.HiLoGuess", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
